export let data=[
    {
        id:1,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:2,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:3,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:4,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:5,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:6,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:7,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:8,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:9,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:10,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:11,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:12,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:13,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:14,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:15,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:16,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:17,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:18,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:19,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:20,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:21,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:22,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:23,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:24,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:25,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:26,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:27,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:28,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:29,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
    {
        id:30,
        name:'raja',
        city:'tuty',
        age:20,
        work:'webdeveloper'
    },
]

export let dnum=5